cads_catalogue_api_service/client.py, cads_catalogue_api_service/database.py, cads_catalogue_api_service/extensions.py, cads_catalogue_api_service/main.py, cads_catalogue_api_service/messages.py, cads_catalogue_api_service/search_utils.py, tests/testing.py
Alternative implementation with no changes to cads-catalogue DB models.
Issues still left:
- many subqueries to load keywords
=> COPDS-1137 reduce db load

cads_catalogue_api_service/search_utils.py
Fix facets bug on keyword selection
=> Copds 1137 improve faceted navigation performance

tests/integration_30_check_urls.py
=> Add url verification integration test

cads_catalogue_api_service/models.py, cads_catalogue_api_service/models/__init__.py, cads_catalogue_api_service/models/base.py, cads_catalogue_api_service/models/schema_org.py, cads_catalogue_api_service/schema_org.py, tests/test_40_schema_org.py
Fixing some schema.org issues and missing data.
Additional discussions are needed. See:
- https://github.com/ecmwf-projects/gecko/issues/80
- https://github.com/ecmwf-projects/cads-forms-json/issues/64
=> COPDS-1255 tuneup schema.org

cads_catalogue_api_service/search_utils.py
During searching for datasets, if a free text is done in combination with keywords (i.e. faceted search), the sorting criterion is ruled by the free text.
=> sorting of queries with faceted search AND free text

cads_catalogue_api_service/client.py, cads_catalogue_api_service/main.py, cads_catalogue_api_service/schema_org.py, schemas/dataset_preview.json, tests/test_10_serializers.py, tests/testing.py
Take advantages of new qa_flag field
=> Showing a new link to the EQC QA tab and latest message

cads_catalogue_api_service/search_utils.py
Implementation of https://jira.ecmwf.int/browse/COPDS-1659
=> advanced operators for dataset search

cads_catalogue_api_service/client.py
=> Do not fail when adaptor.json is missing

cads_catalogue_api_service/collection_ext.py, cads_catalogue_api_service/main.py, cads_catalogue_api_service/schema_org.py, tests/test_40_collection_ext.py
The endpoints are just alias, that redirect to the real resource
=> Added simple form and constraints specific endpoints

cads_catalogue_api_service/client.py, cads_catalogue_api_service/extensions.py, cads_catalogue_api_service/search_utils.py, environment.yml, pyproject.toml
Currently based on a search by id, so is more like a "limit search to these datasets"
=> Starred search implementation

cads_catalogue_api_service/doi.py, cads_catalogue_api_service/main.py, tests/test_40_doi.py
=> Redirect from /doi/xxx/yyy to proper dataset, query by DOI value

cads_catalogue_api_service/contents.py, cads_catalogue_api_service/main.py, cads_catalogue_api_service/models/__init__.py, cads_catalogue_api_service/models/contents.py, pyproject.toml, tests/test_40_contents.py
=> Mock implementation of a contents API

cads_catalogue_api_service/fastapisessionmaker.py
In this way we can easily edit pool configuration is a single centralized way
=> Use engine definition from cads-catalogue

cads_catalogue_api_service/models/schema_org.py, cads_catalogue_api_service/schema_org.py, schemas/schema_org.json, tests/test_40_schema_org.py
=> Fixed image usage in JSON-LD

cads_catalogue_api_service/middlewares.py, tests/test_40_collection_ext.py, tests/test_40_doi.py
[COPDS-2305](https://jira.ecmwf.int/browse/COPDS-2305)
=> chore: no cache for errors

cads_catalogue_api_service/contents.py, tests/test_40_contents.py
```
curl -X 'GET' \
'http://cds2-at-dev-cds.cci2.bopen.eu/api/catalogue/v1/contents/?ctype=application&related_dataset=reanalysis-era5-land&related_dataset=satellite-sea-ice-concentration&sortby=title' \
-H 'accept: application/json'
```
```
{
"count": 1,
"contents": [
{
"type": "application",
"id": "climate-pulse",
"title": "Climate Pulse",
"description": "Climate Pulse visualises near-real-time updates of global average air- and sea-surface temperatures from ECMWF's flagship ERA5 reanalysis",
"published": "2024-09-13T00:00:00",
"updated": "2024-09-13T00:00:00",
"links": [
{
"href": "http://cds2-at-dev-cds.cci2.bopen.eu/api/catalogue/v1/contents/application",
"rel": "parent",
"type": "application/json"
},
{
"href": "http://cds2-at-dev-cds.cci2.bopen.eu/api/catalogue/v1/contents/applicatio …
```
=> COPDS-2429: search by ctype & related_datasets

cads_catalogue_api_service/contents.py
[COPDS-2429](https://jira.ecmwf.int/browse/COPDS-2429)
=> COPDS-2429: no error without results on searching with query params

cads_catalogue_api_service/client.py, cads_catalogue_api_service/sanity_check.py, schemas/dataset_preview.json, tests/test_10_serializers.py, tests/test_60_sanity_check.py, tests/testing.py
[COPDS-2513](https://jira.ecmwf.int/browse/COPDS-2513)
=> COPDS-2513: sanity check

cads_catalogue_api_service/middlewares.py, ci/environment-ci.yml, tests/test_50_middlewares.py
We'll reuse stale cache while updating - see COPDS-2532
=> Improved cache hit

cads_catalogue_api_service/sanity_check.py, tests/test_60_sanity_check.py
=> Trim to 3 tests, and re-sorting changes

cads_catalogue_api_service/config.py, cads_catalogue_api_service/extensions.py
default page size and max page size are not taken from pydantic settings
=> feature: page size configuration from envvars

cads_catalogue_api_service/models/schema_org.py, cads_catalogue_api_service/schema_org.py, tests/test_40_schema_org.py
[COPDS-2654](https://jira.ecmwf.int/browse/COPDS-2654)
=> COPDS-2654: fair improvements

cads_catalogue_api_service/client.py, cads_catalogue_api_service/messages.py, cads_catalogue_api_service/models/base.py, pyproject.toml, schemas/messages.json, tests/test_30_messages.py
[COPDS-2715](https://jira.ecmwf.int/browse/COPDS-2715)
=> COPDS-2715: show_date flag on messages

cads_catalogue_api_service/client.py, tests/conftest.py
Requires https://github.com/ecmwf-projects/cads-catalogue/pull/159
=> COPDS-2774 JSON access to db

cads_catalogue_api_service/client.py, tests/testing.py
[COPDS-2833](https://jira.ecmwf.int/browse/COPDS-2833)
=> COPDS-2833: id and rev on license link

cads_catalogue_api_service/client.py, cads_catalogue_api_service/schema_org.py, cads_catalogue_api_service/search_utils.py, cads_catalogue_api_service/vocabularies.py, schemas/schema_org.json, tests/test_20_vocabularies.py, tests/test_40_schema_org.py, tests/testing.py
Related PRs:
- https://github.com/ecmwf-projects/cads-catalogue/pull/166
[COPDS-2723](https://jira.ecmwf.int/browse/COPDS-2723)
=> COPDS-2827: keywords (facets) and keywords_urls handling

cads_catalogue_api_service/client.py, cads_catalogue_api_service/config.py, cads_catalogue_api_service/sanity_check.py, schemas/dataset_preview.json, tests/test_10_serializers.py, tests/test_60_sanity_check.py, tests/testing.py
Related PR:
- https://github.com/ecmwf-projects/cads-catalogue/pull/164
[COPDS-2799](https://jira.ecmwf.int/browse/COPDS-2799)
=> COPDS-2799: sanity_check expired status & update_frequency dataset field
